Chore templates
TRCDevelopers/Clayium pull request #249
Opened 2024-10-08 14:32 UTC by bqc0n

## What
Add PR template and Issue templates

## Implementation Details
these templates are copied and modified from [GTCEu's github repo](https://github.com/GregTechCEu/GregTech)

## Outcome
Easier creation of issues and easier understanding of PRs.

## Potential Compatibility Issues
None

2024-10-08 16:19 UTC, soramame0256 requested changes

2024-10-08 16:19 UTC, soramame0256 commented on .github/ISSUE_TEMPLATE/001-bug-report.yaml
> +      description: Does this bug occur because of another mod installed alongside GregTech CEu?
This mod isn't GT CEu

2024-10-09 02:43 UTC, bqc0n commented on .github/ISSUE_TEMPLATE/001-bug-report.yaml
> +      description: Does this bug occur because of another mod installed alongside GregTech CEu?
fixed

2024-10-09 02:43 UTC, soramame0256 approved these changes
lgtm

2024-10-09 02:44 UTC, merged